---
swagger: "2.0"
info:
  description: "Photo Server for serving photos to clients."
  version: "0.0.1"
  title: "Photo Server"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "pisara@pisara.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/v2"
tags:
- name: "photos"
  description: "Photo Server"
schemes:
- "http"
paths:
  /photo/next:
    get:
      tags:
      - "photos"
      summary: "Get next photo URL and dimensions from server"
      description: "Gets the photo URL and dimensions of next photo"
      operationId: "next"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties: {}
        400:
          description: "Invalid status value"
      x-swagger-router-controller: "Photos"
  /photo/photo:
    get:
      tags:
      - "photos"
      summary: "Get next photo with given URL from server"
      description: "Gets the photo with given URL"
      operationId: "photo"
      produces:
      - "application/json"
      parameters:
      - name: "URL"
        in: "header"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties: {}
        400:
          description: "Invalid status value"
      x-swagger-router-controller: "Photos"
definitions:
  PhotoMeta:
    properties:
      width:
        type: "integer"
        format: "int64"
      height:
        type: "integer"
        format: "int64"
      URL:
        type: "string"
  Photo:
    type: "object"
    required:
    - "photoUrl"
    properties:
      photoUrl:
        type: "string"
